name: build_conda
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd $HOME
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        sudo apt-get update
        sudo apt-get -y install libgl1-mesa-glx
        sudo apt-get -y install libsm6 libxrender1 libfontconfig1 libxcomposite-dev libxcursor1 libxi6 libxtst6 libxss1 libxrandr2 libasound2 libegl1
        sudo apt-get -y install xvfb
        $HOME/miniconda/bin/conda install xarray numpy scipy pyopengl pytest flake8 six coverage bokeh pyqtgraph matplotlib --yes
        $HOME/miniconda/bin/conda install pyqt --yes
        $HOME/miniconda/bin/conda install -c anaconda netcdf4 --yes
        $HOME/miniconda/bin/conda install -c mavensdc cdflib --yes
        $HOME/miniconda/bin/conda install keyring --yes
    - name: Lint with flake8
      shell: pwsh
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # all Python files should follow PEP8 (except some notebooks, see setup.cfg)
        flake8 jupytext tests
        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Install from source (required for the pre-commit tests)
      shell: pwsh
      run: $HOME/miniconda/bin/conda install .
    - name: Test with pytest
      shell: pwsh
      run: $HOME/miniconda/bin/coverage run --source=. -m tests.tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1